// Auto-generated from Wix textEffectsConfig.ts — run: npm run wix-presets:build
// Source: wix-private/odeditor-packages/.../textEffectsPanel/textEffectsConfig.ts

export const presets = [
  {
    "id": "outline-out-galaxy",
    "name": "Galaxy",
    "defaultText": "Galaxy",
    "panelText": "Galaxy",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-galaxy.png",
    "type": "outline-out",
    "fontFamily": "marzo-w00-regular",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:135)",
      "--layer-blend-mode": "url(#outline-out-dark-glass_blend-mode:multiply)",
      "--text-effects-color-1": "#5A686D",
      "--text-effects-color-2": "#5A686D"
    }
  },
  {
    "id": "neon-sign-remix",
    "name": "Remix",
    "defaultText": "REMIX",
    "panelText": "REMIX",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/neon-sign-remix.png",
    "type": "neon-sign",
    "fontFamily": "orbitron",
    "fontSize": 120,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--shadow-opacity": "0.5",
      "--disable-inner-animation": "initial",
      "--text-color": "#fdfdfd",
      "--inner-animation-speed": "4",
      "--shadow-blur": "0.5",
      "--shadow-color": "#4900FF"
    }
  },
  {
    "id": "outline-out-signal",
    "name": "Signal",
    "defaultText": "Signal",
    "panelText": "Signal",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-signal.png",
    "type": "outline-out",
    "fontFamily": "brandon-grot-w01-light",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:90)",
      "--layer-blend-mode": "url(#outline-out-dark-glass_blend-mode:normal)",
      "--text-effects-color-1": "#00601A",
      "--text-effects-color-2": "#00601A"
    }
  },
  {
    "id": "glass-astro",
    "name": "Astro",
    "defaultText": "Astro",
    "panelText": "ASTRO",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-astro.png",
    "type": "glass",
    "fontFamily": "climate-crisis",
    "fontSize": 105,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#F3F3F3",
      "--text-color": "#2E2A2A",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#35383B",
      "--border-width": "2"
    }
  },
  {
    "id": "sticker-apex",
    "name": "Apex",
    "defaultText": "Apex",
    "panelText": "Apex",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-apex.png",
    "type": "sticker",
    "fontFamily": "feonie",
    "fontSize": 90,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--bg-opacity": "1",
      "--outer-stroke-angle": "0deg",
      "--shadow-opacity": "1",
      "--shadow-distance": "22",
      "--outer-stroke-color": "#83A9FF",
      "--outer-stroke-distance": "17",
      "--shadow-blur": "4",
      "--bg-solid": "#FFFFFF",
      "--text-effects-color-5": "#FFFFFF",
      "--shadow-color": "#FFC4C4",
      "--shadow-angle": "188deg",
      "--outer-stroke": "2",
      "--text-stroke": "0"
    }
  },
  {
    "id": "sticker-space",
    "name": "Space",
    "defaultText": "Space",
    "panelText": "Space",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-space.png",
    "type": "sticker",
    "fontFamily": "enfonix",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--bg-opacity": "1",
      "--outer-stroke-angle": "167deg",
      "--shadow-opacity": "1",
      "--shadow-distance": "10",
      "--outer-stroke-color": "#FF4CF7",
      "--outer-stroke-distance": "17",
      "--shadow-blur": "4",
      "--bg-solid": "#FFFFFF",
      "--text-effects-color-5": "#FFFFFF",
      "--shadow-color": "#EA00FF",
      "--shadow-angle": "148deg",
      "--outer-stroke": "3",
      "--text-stroke": "0"
    }
  },
  {
    "id": "outline-out-jolt",
    "name": "Jolt",
    "defaultText": "Jolt",
    "panelText": "Jolt",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-jolt.png",
    "type": "outline-out",
    "fontFamily": "enfonix",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:45)",
      "--layer-blend-mode": "url(#outline-out-dark-glass_blend-mode:multiply)",
      "--text-effects-color-1": "#000000",
      "--text-effects-color-2": "#000000"
    }
  },
  {
    "id": "shook-beyond",
    "name": "Beyond",
    "defaultText": "Beyond",
    "panelText": "BEYOND",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/shook-beyond.png",
    "type": "shook",
    "fontFamily": "fahkwang",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 700,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#B7BFFF",
      "--text-effects-outline-color": "#FFFFFF",
      "--text-effects-color-2": "#002DFF",
      "--text-effects-color-5": "#E8EBFF",
      "--text-effects-color-1": "#447CFF",
      "--bevel-angle": "315deg",
      "--text-effects-color-4": "#C1CAFF",
      "--layer-count": "5",
      "--layer-spacing": "30",
      "--outline-thickness": "1"
    }
  },
  {
    "id": "letterpress-matte",
    "name": "Matte",
    "defaultText": "Matte",
    "panelText": "Matte",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/letterpress-matte.png",
    "type": "letter-press",
    "fontFamily": "syne-extrabold",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--layer-blend-mode": "normal",
      "--text-effects-color-1": "#FFFFFF",
      "--text-effects-color-2": "#FFFFFF",
      "--text-effects-opacity-color-1": "0.2",
      "--text-shadow": "-1.65px 0px 2.56px rgba(255, 255, 255, 0.5)"
    }
  },
  {
    "id": "sticker-fluffy",
    "name": "Fluffy",
    "defaultText": "Fluffy",
    "panelText": "FLUFFY",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-fluffy.png",
    "type": "sticker",
    "fontFamily": "avatar",
    "fontSize": 90,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bg-opacity": "1",
      "--outer-stroke-angle": "106deg",
      "--shadow-opacity": "1",
      "--shadow-distance": "14",
      "--outer-stroke-color": "#FFFFFF",
      "--outer-stroke-distance": "3",
      "--shadow-blur": "32",
      "--bg-solid": "#63FF4F",
      "--text-effects-color-5": "#63FF4F",
      "--shadow-color": "#63FF4F",
      "--shadow-angle": "90deg",
      "--outer-stroke": "16",
      "--text-stroke": "0"
    }
  },
  {
    "id": "glass-bouncy",
    "name": "Bouncy",
    "defaultText": "Bouncy",
    "panelText": "Bouncy",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-bouncy.png",
    "type": "glass",
    "fontFamily": "vag-rounded-next",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#c19288",
      "--text-color": "#FFE100",
      "--shadow-blur": "url(#glass-shadow_blur:5)",
      "--shadow-color": "#FFE700",
      "--border-width": "6"
    }
  },
  {
    "id": "glass-cloudy",
    "name": "Cloudy",
    "defaultText": "Cloudy",
    "panelText": "Cloudy",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-cloudy.png",
    "type": "glass",
    "fontFamily": "oktah-round",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 700,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#D2F1FF",
      "--text-color": "#87C9F3",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#42B5FF",
      "--border-width": "14"
    }
  },
  {
    "id": "glitch-squish",
    "name": "Squish",
    "defaultText": "Squish",
    "panelText": "SQUISH",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glitch-squish.png",
    "type": "glitch",
    "fontFamily": "modak",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#FF3D00",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#d0cbeb",
      "--inner-animation-speed": "8",
      "--shadow-blur": "0",
      "--text-effects-color-1": "#FFFFFF",
      "--layer-angle": "53deg",
      "--layer-distance": "12"
    }
  },
  {
    "id": "retro-celebrate",
    "name": "Celebrate",
    "defaultText": "Celebrate",
    "panelText": "Celebrate",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/retro-celebrate.png",
    "type": "retro",
    "fontFamily": "dancingscript-regular",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#FC0C84",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#FC0C84",
      "--inner-animation-speed": "18",
      "--shadow-blur": "2",
      "--text-effects-color-1": "#FFEBF8",
      "--bevel-angle": "262deg",
      "--bevel-depth": "10",
      "--text-effects-color-4": "#FC0C84",
      "--layer-count": "4"
    }
  },
  {
    "id": "glass-glaze",
    "name": "Glaze",
    "defaultText": "Glaze",
    "panelText": "GLAZE",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-glaze.png",
    "type": "glass",
    "fontFamily": "climate-crisis",
    "fontSize": 70,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--border-color": "#9B5EFF",
      "--text-color": "#D3C3FF",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#9478E2",
      "--border-width": "2"
    }
  },
  {
    "id": "striped-blossom",
    "name": "Blossom",
    "defaultText": "Blossom",
    "panelText": "Blossom",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/striped-blossom.png",
    "type": "striped",
    "fontFamily": "gaude",
    "fontSize": 50,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--stripe-angle": "225deg",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#FF310F",
      "--inner-animation-speed": "1",
      "--stripe-size": "8",
      "--text-effects-color-1": "#FFA086"
    }
  },
  {
    "id": "striped-level-up",
    "name": "Level Up",
    "defaultText": "Level Up",
    "panelText": "Level Up",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-level-up.png",
    "type": "striped",
    "fontFamily": "press-start-2p",
    "fontSize": 40,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--stripe-angle": "270deg",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#FF00F6",
      "--inner-animation-speed": "1",
      "--stripe-size": "400",
      "--text-effects-color-1": "#36FDFF"
    }
  },
  {
    "id": "sticker-night",
    "name": "Night",
    "defaultText": "Night",
    "panelText": "NIGHT",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-night.png",
    "type": "sticker",
    "fontFamily": "gaude",
    "fontSize": 50,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--bg-opacity": "1",
      "--outer-stroke-angle": "0deg",
      "--shadow-opacity": "1",
      "--shadow-distance": "8",
      "--outer-stroke-color": "#2A183E",
      "--outer-stroke-distance": "0",
      "--shadow-blur": "0",
      "--bg-solid": "#B633FF",
      "--text-effects-color-5": "#B633FF",
      "--shadow-color": "#2A183E",
      "--shadow-angle": "127deg",
      "--outer-stroke": "9",
      "--text-stroke": "0"
    }
  },
  {
    "id": "letterpress-change",
    "name": "Change",
    "defaultText": "Change",
    "panelText": "CHANGE",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/letterpress-change.png",
    "type": "letter-press",
    "fontFamily": "benzin",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--layer-blend-mode": "normal",
      "--text-effects-color-1": "#FFFFFF",
      "--text-effects-color-2": "#FFFFFF",
      "--text-effects-opacity-color-1": "0.2",
      "--text-shadow": "0.36px 0.65px 0.64px rgba(255, 255, 255, 0.8)"
    }
  },
  {
    "id": "glass-refined",
    "name": "Refined",
    "defaultText": "Refined",
    "panelText": "Refined",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-refined.png",
    "type": "glass",
    "fontFamily": "ogg",
    "fontSize": 105,
    "fontStyle": "italic",
    "fontWeight": 700,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#fff",
      "--text-color": "#000",
      "--shadow-blur": "url(#glass-shadow_blur:3)",
      "--shadow-color": "#3d3d3d",
      "--border-width": "6"
    }
  },
  {
    "id": "noisy-organic",
    "name": "Organic",
    "defaultText": "Organic",
    "panelText": "Organic",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/noisy-organic.png",
    "type": "noisy",
    "fontFamily": "feonie",
    "fontSize": 90,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-1": "#228442",
      "--squiggly-level": "url(#noisy_squiggly:7)"
    }
  },
  {
    "id": "neon-sign-cosmic",
    "name": "Cosmic",
    "defaultText": "Cosmic",
    "panelText": "Cosmic",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/neon-sign-cosmic.png",
    "type": "neon-sign",
    "fontFamily": "feonie",
    "fontSize": 90,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--shadow-opacity": "0.5",
      "--disable-inner-animation": "initial",
      "--text-color": "#fff",
      "--inner-animation-speed": "4",
      "--shadow-blur": "0.5",
      "--shadow-color": "#0052ff"
    }
  },
  {
    "id": "glass-frozen-comet",
    "name": "Frozen - Comet",
    "defaultText": "Frozen - Comet",
    "panelText": "Frozen - Comet",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-frozen-comet.png",
    "type": "glass",
    "fontFamily": "tusker-grotesk-ultra-condensed",
    "fontSize": 72,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#FFFFFF",
      "--text-color": "#FF6C6C",
      "--shadow-blur": "url(#glass-shadow_blur:4)",
      "--shadow-color": "#F78461",
      "--border-width": "1"
    }
  },
  {
    "id": "striped-direct",
    "name": "Direct",
    "defaultText": "Direct",
    "panelText": "Direct",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/striped-direct.png",
    "type": "striped",
    "fontFamily": "ogg",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--stripe-angle": "270deg",
      "--disable-inner-animation": "none",
      "--text-effects-color-2": "#000",
      "--inner-animation-speed": "1",
      "--stripe-size": "7",
      "--text-effects-color-1": "#fff"
    }
  },
  {
    "id": "outline-out-dreamy",
    "name": "Dreamy",
    "defaultText": "Dreamy",
    "panelText": "Dreamy",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-dreamy.png",
    "type": "outline-out",
    "fontFamily": "marzo-w00-regular",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:135)",
      "--layer-blend-mode": "url(#outline-out-dark-glass_blend-mode:multiply)",
      "--text-effects-color-1": "#80623B",
      "--text-effects-color-2": "#80623B"
    }
  },
  {
    "id": "outline-out-outline",
    "name": "Outline",
    "defaultText": "Outline",
    "panelText": "Outline",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-outline.png",
    "type": "outline-out",
    "fontFamily": "holy-river",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:45)",
      "--text-effects-color-1": "#B69067",
      "--text-effects-color-2": "#B69067"
    }
  },
  {
    "id": "shook-skate",
    "name": "Skate",
    "defaultText": "Skate",
    "panelText": "Skate",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/shook-skate.png",
    "type": "shook",
    "fontFamily": "wix-madefor-text-v2",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 600,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#FF4300",
      "--text-effects-outline-color": "#0764FF",
      "--text-effects-color-2": "#0764FF",
      "--text-effects-color-5": "#FF4300",
      "--text-effects-color-1": "#FFE426",
      "--bevel-angle": "236deg",
      "--text-effects-color-4": "#978954",
      "--layer-count": "3",
      "--layer-spacing": "27",
      "--outline-thickness": "9"
    }
  },
  {
    "id": "retro-gentle",
    "name": "Gentle",
    "defaultText": "Gentle",
    "panelText": "Gentle",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/retro-gentle.png",
    "type": "retro",
    "fontFamily": "bodoni-moda",
    "fontSize": 65,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#c2d9f6",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#aecdec",
      "--inner-animation-speed": "18",
      "--shadow-blur": "0",
      "--text-effects-color-1": "#005ECB",
      "--bevel-angle": "270deg",
      "--bevel-depth": "24",
      "--text-effects-color-4": "#e0efff",
      "--layer-count": "4"
    }
  },
  {
    "id": "striped-antenna",
    "name": "Antenna",
    "defaultText": "Antenna",
    "panelText": "Antenna",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/striped-antenna.png",
    "type": "striped",
    "fontFamily": "kelly slab",
    "fontSize": 60,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--stripe-angle": "225deg",
      "--disable-inner-animation": "initial",
      "--text-effects-color-2": "#656565",
      "--inner-animation-speed": "1",
      "--stripe-size": "129",
      "--text-effects-color-1": "#BDBDBD"
    }
  },
  {
    "id": "shook-disco",
    "name": "Disco",
    "defaultText": "Disco",
    "panelText": "Disco",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/shook-disco.png",
    "type": "shook",
    "fontFamily": "gaude",
    "fontSize": 50,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#D0FDFF",
      "--text-effects-outline-color": "#EE74C3",
      "--text-effects-color-2": "#FF7357",
      "--text-effects-color-5": "#FFDF8B",
      "--text-effects-color-1": "#FFFFFF",
      "--bevel-angle": "315deg",
      "--text-effects-color-4": "#DAFBAC",
      "--layer-count": "5",
      "--layer-spacing": "41",
      "--outline-thickness": "4"
    }
  },
  {
    "id": "glass-turbo",
    "name": "Turbo",
    "defaultText": "TURBO",
    "panelText": "TURBO",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-turbo.png",
    "type": "glass",
    "fontFamily": "press-start-2p",
    "fontSize": 55,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#FFECE1",
      "--text-color": "#BC9331",
      "--shadow-blur": "url(#glass-shadow_blur:4)",
      "--shadow-color": "#FFC101",
      "--border-width": "10"
    }
  },
  {
    "id": "glass-core",
    "name": "Core",
    "defaultText": "Core",
    "panelText": "Core",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-core.png",
    "type": "glass",
    "fontFamily": "winner-college",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--border-color": "#008dff",
      "--text-color": "#6CAFCE",
      "--shadow-blur": "url(#glass-shadow_blur:7)",
      "--shadow-color": "#2266ea",
      "--border-width": "1"
    }
  },
  {
    "id": "sticker-point",
    "name": "Point",
    "defaultText": "Point",
    "panelText": "Point",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/sticker-point.png",
    "type": "sticker",
    "fontFamily": "press-start-2p",
    "fontSize": 40,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bg-opacity": "1",
      "--outer-stroke-angle": "167deg",
      "--shadow-opacity": "1",
      "--shadow-distance": "6",
      "--outer-stroke-color": "#FFFFFF",
      "--outer-stroke-distance": "6",
      "--shadow-blur": "0",
      "--bg-solid": "#0040FF",
      "--text-effects-color-5": "#0040FF",
      "--shadow-color": "#90BAFF",
      "--shadow-angle": "148deg",
      "--outer-stroke": "8",
      "--text-stroke": "0"
    }
  },
  {
    "id": "bauhaus-direct",
    "name": "Direct",
    "defaultText": "Direct",
    "panelText": "Direct",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/bauhaus-direct.png",
    "type": "bauhaus",
    "fontFamily": "digital",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#B5C092",
      "--shadow-distance": "6",
      "--text-effects-color-2": "#0E0E0E",
      "--layer-blend-mode": "screen",
      "--text-effects-color-1": "#7A756C",
      "--bevel-angle": "69deg"
    }
  },
  {
    "id": "matrix-funk",
    "name": "Funk",
    "defaultText": "Funk",
    "panelText": "Funk",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/matrix-funk.png",
    "type": "matrix",
    "fontFamily": "suez one",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--disable-inner-animation": "initial",
      "--mask-position": "1",
      "--inner-animation-speed": "7",
      "--text-effects-color-1": "#7ED3D6",
      "--mask-blur": "1",
      "--text-blur": "1"
    }
  },
  {
    "id": "bauhaus-glow",
    "name": "Glow",
    "defaultText": "Glow",
    "panelText": "Glow",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/bauhaus-glow.png",
    "type": "bauhaus",
    "fontFamily": "neue-haas-grotesk-display-pro",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 700,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#000cff",
      "--shadow-distance": "6",
      "--text-effects-color-2": "#45ff00",
      "--layer-blend-mode": "screen",
      "--text-effects-color-1": "#f00",
      "--bevel-angle": "180deg"
    }
  },
  {
    "id": "3d-friction",
    "name": "Friction",
    "defaultText": "Friction",
    "panelText": "Friction",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/3d-friction.png",
    "type": "3d",
    "fontFamily": "midnight-terror",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--fill-color": "#fff",
      "--text-shadow-3": "0px 0px 0px #60bfeb",
      "--text-stroke-opacity": "100%",
      "--text-shadow-1": "0px 2px 3px #0219AA",
      "--text-shadow-2": "1px 2px 2px rgba(6, 85, 255, 0.31)",
      "--fill-opacity": "100%",
      "--text-stroke-color": "#fff",
      "--text-stroke": "3"
    }
  },
  {
    "id": "noisy-blurry",
    "name": "Blurry",
    "defaultText": "Blurry",
    "panelText": "Blurry",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/noisy-blurry.png",
    "type": "noisy",
    "fontFamily": "monoton",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-1": "#000000",
      "--squiggly-level": "url(#noisy_squiggly:7)"
    }
  },
  {
    "id": "3d-shine",
    "name": "Shine",
    "defaultText": "Shine",
    "panelText": "Shine",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/3d-shine.png",
    "type": "3d",
    "fontFamily": "bandito-script",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--fill-color": "#00ff32",
      "--text-shadow-3": "0px 0px 12px #13ff00",
      "--text-stroke-opacity": "1",
      "--text-shadow-1": "0px 2px 0px rgba(0, 0, 0, 0)",
      "--text-shadow-2": "0px 2px 1px rgba(0, 0, 0, 0)",
      "--fill-opacity": "1",
      "--text-stroke-color": "#2ac14d",
      "--text-stroke": "1"
    }
  },
  {
    "id": "glass-flare",
    "name": "Flare",
    "defaultText": "Flare",
    "panelText": "Flare",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-flare.png",
    "type": "glass",
    "fontFamily": "p22-posada",
    "fontSize": 72,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--border-color": "#FF00F6",
      "--text-color": "#FF00F6",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#0043FF",
      "--border-width": "4"
    }
  },
  {
    "id": "letterpress-echo",
    "name": "Echo",
    "defaultText": "Echo",
    "panelText": "Echo",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/letterpress-echo.png",
    "type": "letter-press",
    "fontFamily": "bodoni-w01-poster",
    "fontSize": 65,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--layer-blend-mode": "normal",
      "--text-effects-color-1": "#FFFFFF",
      "--text-effects-color-2": "#FFFFFF",
      "--text-effects-opacity-color-1": "0.2",
      "--text-shadow": "1.3px 0.82px 0.8px rgba(255, 255, 255, 0.5)"
    }
  },
  {
    "id": "noisy-hollow",
    "name": "Hollow",
    "defaultText": "Hollow",
    "panelText": "Hollow",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/noisy-hollow.png",
    "type": "noisy",
    "fontFamily": "eschaton",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-1": "#3B6133",
      "--squiggly-level": "url(#noisy_squiggly:6)"
    }
  },
  {
    "id": "outline-out-hyper",
    "name": "Hyper",
    "defaultText": "Hyper",
    "panelText": "Hyper",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/outline-out-hyper.png",
    "type": "outline-out",
    "fontFamily": "ca-smut",
    "fontSize": 120,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--bevel-angle": "url(#outline-out-lightA3_azimuth:45)",
      "--layer-blend-mode": "url(#outline-out-dark-glass_blend-mode:multiply)",
      "--text-effects-color-1": "#000000",
      "--text-effects-color-2": "#000000"
    }
  },
  {
    "id": "noisy-breeze",
    "name": "Breeze",
    "defaultText": "Breeze",
    "panelText": "Breeze",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/noisy-breeze.png",
    "type": "noisy",
    "fontFamily": "zing-rust",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-1": "#806230",
      "--squiggly-level": "url(#noisy_squiggly:7)"
    }
  },
  {
    "id": "glass-moment",
    "name": "Moment",
    "defaultText": "moment",
    "panelText": "moment",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-moment.png",
    "type": "glass",
    "fontFamily": "unifrakturmaguntia",
    "fontSize": 137,
    "fontStyle": "italic",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--border-color": "#000",
      "--text-color": "#000",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#363636",
      "--border-width": "4"
    }
  },
  {
    "id": "glass-noise",
    "name": "Noise",
    "defaultText": "Noise",
    "panelText": "Noise",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/glass-noise.png",
    "type": "glass",
    "fontFamily": "benzin",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 700,
    "textTransform": "uppercase",
    "textAlign": "center",
    "vars": {
      "--border-color": "#A3E50B",
      "--text-color": "#A3E50B",
      "--shadow-blur": "url(#glass-shadow_blur:2)",
      "--shadow-color": "#A3E50B",
      "--border-width": "7"
    }
  },
  {
    "id": "3d-smash",
    "name": "Smash",
    "defaultText": "Smash",
    "panelText": "Smash",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/3d-smash.png",
    "type": "3d",
    "fontFamily": "ogg",
    "fontSize": 80,
    "fontStyle": "italic",
    "fontWeight": 700,
    "textTransform": "none",
    "textAlign": "center",
    "vars": {
      "--fill-color": "#5205FF",
      "--text-shadow-3": "0px 0px 10px #5205FF",
      "--text-stroke-opacity": "1",
      "--text-shadow-1": "0px 0px 5px #ff00000d",
      "--text-shadow-2": "0px 0px 4px #5205FF",
      "--fill-opacity": "1",
      "--text-stroke-color": "#460EC6",
      "--text-stroke": "1"
    }
  },
  {
    "id": "bauhaus-stellar",
    "name": "Stellar",
    "defaultText": "Stellar",
    "panelText": "Stellar",
    "thumbnailUrl": "https://static.parastorage.com/services/santa-resources/dist/editor/interchangePanel/textEffect/v2/bauhaus-stellar.png",
    "type": "bauhaus",
    "fontFamily": "pirata-one",
    "fontSize": 80,
    "fontStyle": "normal",
    "fontWeight": 400,
    "textTransform": "capitalize",
    "textAlign": "center",
    "vars": {
      "--text-effects-color-3": "#FF9988",
      "--shadow-distance": "6",
      "--text-effects-color-2": "#00439A",
      "--layer-blend-mode": "screen",
      "--text-effects-color-1": "#009DFF",
      "--bevel-angle": "124deg"
    }
  }
];
